name: "Sanity"
on:
  pull_request
jobs:
  cypress:
    name: "Cypress"
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - name: npm install and run
        run: |
          npm ci
          npm start & npx wait-on http://localhost:3000
      - name: Running Cypress tests
        run: docker run -it --network=host -v ${PWD}:/e2e -w /e2e cypress/included:9.2.0
        timeout-minutes: 30

  API:
    name: "API-testing"
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - name: Install Node Packages
        run: npm ci
        timeout-minutes: 10
      - name: run api tests
        run: npm run api-test
        timeout-minutes: 30